name: zip files

on:
  push:
    branches:
      - main

jobs:
  zip-repo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: modify module.prop
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          sed -i "/^updateJson=/d" module.prop
          sed -i "s/^version=.*/version=${RELEASE_VERSION}/" module.prop

      - name: Create ZIP
        run: |
          zip -r wadbd-${{ github.event.release.tag_name }}.zip . \
            --exclude changelog.md README.md updateJson .git .github .gitignore

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: wadbd-${{ github.event.release.tag_name }}
          path: wadbd-${{ github.event.release.tag_name }}.zip

      - name: Attach ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: wadbd-${{ github.event.release.tag_name }}.zip
          
