name: zip files

on:
  push:
    branches:
      - main

jobs:
  zip-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Commit Hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: modify module.prop
        run: |
          sed -i "/^updateJson=/d" module.prop
          sed -i "s/^version=.*/version=${COMMIT_HASH}/" module.prop

      - name: create ZIP
        run: |
          zip -r wadbd-${COMMIT_HASH}.zip . \
            --exclude changelog.md README.md updateJson .git .github .gitignore

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: wadbd-${{ env.COMMIT_HASH }}
          path: wadbd-${{ env.COMMIT_HASH }}.zip
